---
version: '2.1'

services:
  service-auth-provider-app:
    image: hmcts/service-auth-provider-app:latest
    environment:
      - jwtKey=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
#      - Add key for any microservice that will be used: template-management
      - microserviceKeys_em_gw=AAAAAAAAAAAAAAAA
      - microserviceKeys_dg_docassembly_api=AAAAAAAAAAAAAAAA
      - microserviceKeys_dg_template_management_api=AAAAAAAAAAAAAAAA
      #      logging env vars
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=service-auth-provider-app
      - REFORM_TEAM=rpe
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=rpe
      - PACKAGES_NAME=service-auth-provider-app
      - PACKAGES_VERSION=unkown
      - TESTING_SUPPORT_ENABLED=true
    ports:
      - 4502:8489

  smtp-server:
    image: mailhog/mailhog

  rpa-dg-template-management-api:
    image: hmcts.azurecr.io/hmcts/dg-tmpl-mgmt:latest
    environment:
      - S2S_BASE_URI=http://service-auth-provider-app:8489
      - IDAM_API_BASE_URI=http://betadevaccidamapplb.reform.hmcts.net
      - APPINSIGHTS_INSTRUMENTATIONKEY=test-key
    links:
      - service-auth-provider-app
    depends_on:
      - dm-store-db
      - service-auth-provider-app
    ports:
      - 4603:8080

  dm-store-db:
    image: hmcts/dm-store-db:latest