docassembly-api:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 8080
  readinessDelay: 20
  readinessTimeout: 20
  readinessFailureThreshold: 7
  readinessPeriod: 15
  livenessDelay: 20
  livenessTimeout: 20
  livenessPeriod: 15
  livenessFailureThreshold: 7
  keyVaults:
    rpa:
      resourceGroup: rpa
      secrets:
        - AppInsightsInstrumentationKey
    s2s:
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-dg-docassembly-api
  environment:
    REFORM_SERVICE_NAME: dg-docassembly
    REFORM_TEAM: evidence
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    PACKAGES_NAME: dg-docassembly
    PACKAGES_PROJECT: evidence
    PACKAGES_ENVIRONMENT: preview
    JSON_CONSOLE_PRETTY_PRINT: false
    LOG_OUTPUT: single
    ROOT_LOGGING_LEVEL: INFO
    LOG_LEVEL_SPRING_WEB: INFO
    LOG_LEVEL_DM: INFO
    ENDPOINTS_HEALTH_SENSITIVE: false
    ENDPOINTS_INFO_SENSITIVE: false
    S2S_NAMES_WHITELIST: em_api,em_gw,ccd_gw,ccd_data,sscs,dg_tmpl_mgmt, dg_docassembly, divorce_document_upload,divorce_document_generator,probate_backend,jui_webapp,pui_webapp
    CASE_WORKER_ROLES: caseworker-probate,caseworker-cmc,caseworker-sscs,caseworker-divorce
    ENABLE_IDAM_HEALTH_CHECK: false
    ENABLE_S2S_HEALTH_CHECK: false
    SERVER_PORT: 8080
    IDAM_API_BASE_URI: https://idam-api-idam-aat.service.core-compute-idam-aat.internal/
    S2S_BASE_URI: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    IDAM_WEBSHOW_WHITELIST: https://em-show-aat.service.core-compute-aat.internal/oauth2/callback
    DM_STORE_APP_URL: http://dm-store-aat.service.core-compute-aat.internal
    DG_TEMPLATE_MANAGEMENT_API: http://dg-tmpl-mgmt-aat.service.core-compute-aat.internal
