---
spring:
  main:
    allow-bean-definition-overriding: true

test:
  url: ${TEST_URL:http://localhost:8080}

idam:
  api:
    url: ${IDAM_API_BASE_URI:http://localhost:4501}
  client:
    id: ${OAUTH_CLIENT:webshow}
    secret: ${FUNCTIONAL_TEST_CLIENT_OAUTH_SECRET:AAAAAAAAAAAAAAAA}
    redirect_uri: ${IDAM_WEBSHOW_WHITELIST:http://localhost:8080/oauth2redirect}

s2s:
  api:
    url: http://localhost:4502
    secret: AAAAAAAAAAAAAAAA
    serviceName: em_gw
    ccdGwSecret: AAAAAAAAAAAAAAAA
    ccdGwServiceName: ccd_gw

ccd-def:
  api:
    url: http://localhost:4451

document_management:
  url: docker ps

core_case_data:
  api:
    url: http://localhost:4452

toggle:
  enable_form_definition_endpoint: ${ENABLE_FORM_DEFINITION_ENDPOINT:false}
  enable_template_rendition_endpoint: ${ENABLE_TEMPLATE_RENDITION_ENDPOINT:true}
